name: Security Audit

on: [push, pull_request]

jobs:
  audit:
    name: Audit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: rustsec/audit-check@v1.4.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
