name: Docker Image

on:
  workflow_dispatch:

jobs:
  package:
    name: Build 22.04 Docker Image
    timeout-minutes: 60
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: docker build -t ghcr.io/jonlamb-gh/trace-recorder-to-ctf:latest .

      - name: Push docker image
        run: docker push ghcr.io/jonlamb-gh/trace-recorder-to-ctf:latest
