name: Release

# Push events to matching v*, i.e. v1.0, v20.15.10
on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    name: Build Release Artifacts
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Print version
        run: |
          RELEASE_TAG=${{ github.ref }}
          RELEASE_TAG="${RELEASE_TAG#refs/tags/}"
          RELEASE_VERSION="${RELEASE_TAG#v}"
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
          echo "Release tag: $RELEASE_TAG"
          echo "Release version: $RELEASE_VERSION"

      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends --assume-yes patchelf gzip cmake make gcc g++ build-essential
          sudo apt-get install --no-install-recommends --assume-yes libssl-dev libglib2.0-dev pkg-config libtool flex bison autoconf automake

      - name: Install toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Fetch dependencies
        run: cargo fetch

      - name: Build release binaries
        run: cargo build --release

      - name: Create github release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          name: Release ${{ env.RELEASE_VERSION }}
          files: |
            target/release/trace-recorder-to-ctf
